00 configure environment
JoaresMiranda/2019-surfshop-poc pull request #54
Opened 2020-10-12 12:33 UTC by JoaresMiranda

Update README and install dependencies

2020-10-12 14:32 UTC, marceloglacial requested changes

2020-10-12 14:32 UTC, marceloglacial commented on package.json
> +{
Move this file to front-end folder. 
All the project dependencies for front-end should live on front-end folder

2020-10-12 14:32 UTC, marceloglacial commented on README.md
> +- [Install npm](https://www.npmjs.com/get-npm)
Add a step do change folder to front-end

2020-10-12 19:50 UTC, JoaresMiranda commented
Move files to front-end folder and create how to

2020-10-13 11:54 UTC, marceloglacial requested changes

2020-10-13 11:54 UTC, marceloglacial commented on README.md
> +## How to install
Please update the install  command. Now all the files live on the front-end folder

2020-10-13 11:54 UTC, marceloglacial commented on front-end/package.json
> +{
Delete package-lock.json from the **root folder**.

2020-10-13 13:11 UTC, marceloglacial requested changes

2020-10-13 13:11 UTC, marceloglacial commented on .gitignore
> +package-lock.json
Remove it from gitignore.

2020-10-13 13:11 UTC, marceloglacial commented on .gitignore
>  # Thumbnails
Move this file to front-end folder. Remember, all the files live in the front-end folder

2020-10-15 00:00 UTC, marceloglacial approved these changes

2020-10-15 00:01 UTC, merged